# Generated by Django 5.0.6 on 2024-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('base_salary', models.FloatField()),
                ('bonuses', models.FloatField()),
                ('deductions', models.FloatField()),
                ('net_salary', models.FloatField(editable=False)),
            ],
        ),
    ]
