# Generated by Django 5.0.6 on 2024-06-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='net_salary',
            field=models.FloatField(),
        ),
    ]
