# Generated by Django 5.0.6 on 2024-06-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_salary_net_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='net_salary',
            field=models.FloatField(editable=False),
        ),
    ]
