# Generated by Django 5.0.6 on 2024-06-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_salary_employee_name_salary_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='overtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.FloatField(help_text='gross salary'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonuses',
            field=models.FloatField(editable=False, help_text='additional amount alongside gross salary'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='deductions',
            field=models.FloatField(help_text='all deductions from gross salary'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='enter your last name', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text=' username', max_length=70, unique=True),
        ),
    ]
