# Generated by Django 5.0.6 on 2024-06-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_salary_overtime_alter_salary_base_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='overtime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
